USE testDatabase;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'test') DROP TABLE test;
CREATE TABLE test (
       binary binary(2),
       varbinary varbinary(16),
       -- boolean boolean,
       bit bit,
       char char(16),
       varchar varchar(16),
       datetime datetime,
       smalldatetime smalldatetime,
       tinyint tinyint,
       smallint smallint,
       int int,
       bigint bigint,
       decimal decimal,
       numeric numeric,
       float float,
       real real,
       money money,
       smallmoney smallmoney,
       -- sensitivity sensitivity,
       text text,
       image image,
       nchar nchar(16),
       nvarchar nvarchar(16),
       ntext ntext
       );
INSERT INTO test VALUES (
       -- 16,
       -- 16777216,
       -- CONVERT(VARBINARY(256), '0x100000', 1),
       -- 65536,
       -- power(2, 8) - 1,
       -- power(2, 8) - 1,
       -- power(2, 8) - 1,
       1,
       1,
       1,
       'harro',
       'harro',
       34000,
       34000,
       12,
       12,
       12,
       12,
       12.1,
       12.1,
       12.1,
       12.1,
       -- CONVERT(MONEY, '$12.50'),
       -- CONVERT(MONEY, '$12.50'),
       -- $5294967293.00,
       -$4294967296.50,
       $12.50,
       'oeutnh',
       'oeutnh',
       'oeutnh',
       N'oeöutnh',
       N'日本語'
       );
go
